name: Deploy to GCP Cloud Functions

on:
  push:
    branches:
      - main  # Runs deployment when pushing to the main branch

jobs:
  deploy:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 --decode > "$HOME"/gcp-key.json
          gcloud auth activate-service-account --key-file="$HOME"/gcp-key.json
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Deploy to Cloud Functions
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCF_FUNCTION_NAME: ${{ secrets.GCF_FUNCTION_NAME }}
          GCF_ENTRY_POINT: ${{ secrets.GCF_ENTRY_POINT }}
        run: |
          gcloud functions deploy "$GCF_FUNCTION_NAME" \
            --runtime python310 \
            --trigger-http \
            --allow-unauthenticated \
            --region "$GCP_REGION" \
            --entry-point "$GCF_ENTRY_POINT" \
            --source ./project/gcf-facial-recognition/

